name: Run pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install dependencies
      run: pip install -r requirements.txt  # Replace with your actual requirements file

    - name: Run pytest
      run: |
        pytest --junitxml=pytest_report.xml
        echo "::set-output name=report::pytest_report.xml"

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: pytest_report.xml
